a = int(input())
b = int(input())
print("это + :" + a + b)
print("это - :" + a - b)
print("это * :" + a * b)
print("это / :" + a / b)
print("это & :" + a & b)
print("это % :" + a % b)
print("это ** :" + a ** b)

input()
